# GoReleaser configuration for autospec
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download
    - go test ./...

builds:
  - id: autospec
    binary: autospec
    main: ./cmd/autospec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      # Set version in internal/build (used for dev gating via IsDevBuild/MultiAgentEnabled)
      - -X github.com/ariel-frischer/autospec/internal/build.Version={{.Version}}
      - -X github.com/ariel-frischer/autospec/internal/build.Commit={{.ShortCommit}}
      - -X github.com/ariel-frischer/autospec/internal/build.BuildDate={{.Date}}
      # Set version in internal/cli/util (used for version command display)
      - -X github.com/ariel-frischer/autospec/internal/cli/util.Version={{.Version}}
      - -X github.com/ariel-frischer/autospec/internal/cli/util.Commit={{.ShortCommit}}
      - -X github.com/ariel-frischer/autospec/internal/cli/util.BuildDate={{.Date}}

archives:
  - id: autospec-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Changelog disabled - using curated CHANGELOG.md instead of commits
# Release notes extracted via .release/extract-changelog.sh
changelog:
  disable: true

release:
  github:
    owner: ariel-frischer
    name: autospec
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## autospec {{ .Version }}

    **Release Date:** {{ .Date }}

    ### Installation

    #### Using install script (recommended):
    ```bash
    curl -fsSL https://raw.githubusercontent.com/ariel-frischer/autospec/main/install.sh | sh
    ```

    #### Manual installation:
    Download the appropriate binary for your platform from the assets below and extract it to your PATH.

    ### Checksums
    Verify your download using the checksums provided below.

  footer: |
    ---
    **Full Changelog**: https://github.com/ariel-frischer/autospec/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Reporting Issues
    Found a bug or have a feature request? Please [open an issue](https://github.com/ariel-frischer/autospec/issues/new/choose).

# Homebrew tap (optional - uncomment when ready to publish to Homebrew)
# brews:
#   - name: autospec
#     homepage: https://github.com/ariel-frischer/autospec
#     description: "Automated SpecKit workflow validation for Claude Code"
#     license: Apache-2.0
#     repository:
#       owner: ariel-frischer
#       name: homebrew-tap
#     commit_author:
#       name: goreleaser
#       email: noreply@anthropic.com
#     folder: Formula
#     install: |
#       bin.install "autospec"

# Docker images (optional - uncomment when ready)
# dockers:
#   - image_templates:
#       - "ghcr.io/ariel-frischer/autospec:{{ .Version }}-amd64"
#       - "ghcr.io/ariel-frischer/autospec:latest-amd64"
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"

snapshot:
  version_template: "{{ .Version }}-next"

dist: dist
